import { useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { Link, useParams } from "react-router-dom";
import { Activity, ArrowLeft, BadgeDollarSign, GitBranch, Scale, Stethoscope } from "lucide-react";
import api, { getApiError } from "../../lib/api";

type Animal={id:number;identifier:string;sex:string;weight_kg:string|null;breeding_status:string};
type Herd={id:number;name:string;species:string;head_count:number;traceability_batch_id:number|null;traceability_code:string|null;animals:Animal[];health_events:Array<{id:number;event_type:string;occurred_on:string;description:string}>;production_records:Array<{id:number;record_type:string;recorded_on:string;quantity:string;unit:string}>;breeding_records:Array<{id:number;event_type:string;occurred_on:string;outcome:string}>;financial_records:Array<{id:number;record_type:string;category:string;amount:string;occurred_on:string}>;alerts:Array<{id:number;level:string;message:string}>;profitability:{income:string;expenses:string;net:string}};
const today=new Date().toISOString().slice(0,10); const field="rounded-lg border border-slate-300 p-2.5 dark:border-gray-700 dark:bg-gray-950";

export default function HerdRecord(){
 const {id}=useParams(); const [herd,setHerd]=useState<Herd|null>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
 const [animal,setAnimal]=useState({identifier:"",sex:"unknown",date_of_birth:"",estimated_age_months:"",weight_kg:"",acquisition_type:"unknown",acquisition_date:"",breeding_status:"not_recorded"});
 const [health,setHealth]=useState({event_type:"inspection",occurred_on:today,description:"",animal_id:"",product_or_vaccine:"",administered_by:"",withdrawal_end_date:""});
 const [production,setProduction]=useState({record_type:"eggs",recorded_on:today,quantity:"",unit:"item",notes:""}); const [weight,setWeight]=useState({animal_id:"",recorded_on:today,weight_kg:""});
 const [breeding,setBreeding]=useState({event_type:"mating",occurred_on:today,animal_id:"",expected_due_date:"",outcome:"",notes:""}); const [finance,setFinance]=useState({record_type:"expense",category:"feed",amount:"",occurred_on:today,description:""}); const [movement,setMovement]=useState({event_type:"movement",location:"",quantity:"",description:""});
 const load=async()=>{try{setHerd((await api.get<Herd>(`/api/livestock/herds/${id}/`)).data);}catch(reason){setError(getApiError(reason,"Herd or flock record could not be loaded."));}}; useEffect(()=>{void load();},[id]);
 const submit=async(event:FormEvent,path:string,data:Record<string,unknown>,message:string,reset:()=>void)=>{event.preventDefault();setBusy(true);setError("");try{await api.post(path,data);reset();setNotice(message);await load();}catch(reason){setError(getApiError(reason,"The record could not be saved."));}finally{setBusy(false);}};
 if(!herd)return <main className="p-6">{error||"Loading livestock record…"}</main>;
 return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><Link to="/app/livestock" className="inline-flex items-center gap-2 font-semibold text-green-700"><ArrowLeft size={18}/>Livestock dashboard</Link><header className="rounded-2xl bg-emerald-900 p-6 text-white"><h1 className="text-2xl font-bold">{herd.name}</h1><p className="mt-1">{herd.species.replaceAll("_"," ")} · {herd.head_count} head · Traceability {herd.traceability_code||"not initialized"}</p></header>{error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</div>}{notice&&<div role="status" className="rounded-xl bg-green-50 p-4 text-green-800">{notice}</div>}
 {herd.alerts.length>0&&<section className="rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-bold">Active alerts</h2>{herd.alerts.map(x=><p className="mt-2 text-sm" key={x.id}><strong>{x.level.toUpperCase()}:</strong> {x.message}</p>)}</section>}
 <section className="grid gap-5 lg:grid-cols-2">
 <RecordForm title="Add animal or bird" icon={<Activity/>} onSubmit={e=>void submit(e,`/api/livestock/herds/${id}/animals/`,animal,"Animal record added.",()=>setAnimal({...animal,identifier:"",weight_kg:""}))}><input required className={field} placeholder="Ear tag, ring or batch identifier" value={animal.identifier} onChange={e=>setAnimal({...animal,identifier:e.target.value})}/><select className={field} value={animal.sex} onChange={e=>setAnimal({...animal,sex:e.target.value})}><option value="unknown">Unknown sex</option><option value="female">Female</option><option value="male">Male</option></select><label className="text-xs">Date of birth<input type="date" className={`${field} mt-1 w-full`} value={animal.date_of_birth} onChange={e=>setAnimal({...animal,date_of_birth:e.target.value})}/></label><input type="number" min="0" className={field} placeholder="Estimated age (months)" value={animal.estimated_age_months} onChange={e=>setAnimal({...animal,estimated_age_months:e.target.value})}/><input type="number" min="0" step="0.01" className={field} placeholder="Current weight kg" value={animal.weight_kg} onChange={e=>setAnimal({...animal,weight_kg:e.target.value})}/><select className={field} value={animal.acquisition_type} onChange={e=>setAnimal({...animal,acquisition_type:e.target.value})}>{["birth","purchase","transfer","unknown"].map(x=><option key={x}>{x}</option>)}</select><label className="text-xs">Acquisition date<input type="date" className={`${field} mt-1 w-full`} value={animal.acquisition_date} onChange={e=>setAnimal({...animal,acquisition_date:e.target.value})}/></label><select className={field} value={animal.breeding_status} onChange={e=>setAnimal({...animal,breeding_status:e.target.value})}>{["not_recorded","not_breeding","breeding","pregnant","lactating"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></RecordForm>
 <RecordForm title="Health, vaccination or mortality" icon={<Stethoscope/>} onSubmit={e=>void submit(e,`/api/livestock/herds/${id}/health-events/`,health,"Health event recorded.",()=>setHealth({...health,description:"",product_or_vaccine:""}))}><select className={field} value={health.event_type} onChange={e=>setHealth({...health,event_type:e.target.value})}>{["vaccination","treatment","illness","injury","inspection","quarantine","birth","death"].map(x=><option key={x}>{x}</option>)}</select><input required type="date" className={field} value={health.occurred_on} onChange={e=>setHealth({...health,occurred_on:e.target.value})}/><select className={field} value={health.animal_id} onChange={e=>setHealth({...health,animal_id:e.target.value})}><option value="">Whole herd/flock</option>{herd.animals.map(x=><option value={x.id} key={x.id}>{x.identifier}</option>)}</select><input className={field} placeholder="Vaccine or product (record only)" value={health.product_or_vaccine} onChange={e=>setHealth({...health,product_or_vaccine:e.target.value})}/><textarea required className={`${field} sm:col-span-2`} placeholder="Observation or event description" value={health.description} onChange={e=>setHealth({...health,description:e.target.value})}/><input className={field} placeholder="Administered/inspected by" value={health.administered_by} onChange={e=>setHealth({...health,administered_by:e.target.value})}/><label className="text-xs">Withdrawal period ends<input type="date" className={`${field} mt-1 w-full`} value={health.withdrawal_end_date} onChange={e=>setHealth({...health,withdrawal_end_date:e.target.value})}/></label></RecordForm>
 <RecordForm title="Production or feed record" icon={<Scale/>} onSubmit={e=>void submit(e,`/api/livestock/herds/${id}/production/`,production,"Production record added.",()=>setProduction({...production,quantity:"",notes:""}))}><select className={field} value={production.record_type} onChange={e=>setProduction({...production,record_type:e.target.value})}>{["eggs","milk","manure","live_weight","feed_used","mortality"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input required type="date" className={field} value={production.recorded_on} onChange={e=>setProduction({...production,recorded_on:e.target.value})}/><input required type="number" min="0" step="0.001" className={field} placeholder="Quantity" value={production.quantity} onChange={e=>setProduction({...production,quantity:e.target.value})}/><input required className={field} placeholder="Unit (items, litres, kg)" value={production.unit} onChange={e=>setProduction({...production,unit:e.target.value})}/><textarea className={`${field} sm:col-span-2`} placeholder="Notes" value={production.notes} onChange={e=>setProduction({...production,notes:e.target.value})}/></RecordForm>
 <RecordForm title="Weight history" icon={<Scale/>} onSubmit={e=>void submit(e,`/api/livestock/animals/${weight.animal_id}/weights/`,weight,"Weight recorded.",()=>setWeight({...weight,weight_kg:""}))}><select required className={field} value={weight.animal_id} onChange={e=>setWeight({...weight,animal_id:e.target.value})}><option value="">Select animal</option>{herd.animals.map(x=><option value={x.id} key={x.id}>{x.identifier}</option>)}</select><input required type="date" className={field} value={weight.recorded_on} onChange={e=>setWeight({...weight,recorded_on:e.target.value})}/><input required type="number" min="0.01" step="0.01" className={field} placeholder="Weight kg" value={weight.weight_kg} onChange={e=>setWeight({...weight,weight_kg:e.target.value})}/></RecordForm>
 <RecordForm title="Breeding & pregnancy" icon={<GitBranch/>} onSubmit={e=>void submit(e,`/api/livestock/herds/${id}/breeding/`,breeding,"Breeding record added.",()=>setBreeding({...breeding,outcome:"",notes:""}))}><select className={field} value={breeding.event_type} onChange={e=>setBreeding({...breeding,event_type:e.target.value})}>{["mating","insemination","pregnancy_check","birth","weaning"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input required type="date" className={field} value={breeding.occurred_on} onChange={e=>setBreeding({...breeding,occurred_on:e.target.value})}/><select className={field} value={breeding.animal_id} onChange={e=>setBreeding({...breeding,animal_id:e.target.value})}><option value="">Whole group</option>{herd.animals.map(x=><option value={x.id} key={x.id}>{x.identifier}</option>)}</select><label className="text-xs">Expected due date<input type="date" className={`${field} mt-1 w-full`} value={breeding.expected_due_date} onChange={e=>setBreeding({...breeding,expected_due_date:e.target.value})}/></label><textarea className={`${field} sm:col-span-2`} placeholder="Outcome and notes" value={breeding.outcome} onChange={e=>setBreeding({...breeding,outcome:e.target.value})}/></RecordForm>
 <RecordForm title="Expenses & income" icon={<BadgeDollarSign/>} onSubmit={e=>void submit(e,`/api/livestock/herds/${id}/financial-records/`,finance,"Financial record added.",()=>setFinance({...finance,amount:"",description:""}))}><select className={field} value={finance.record_type} onChange={e=>setFinance({...finance,record_type:e.target.value})}><option value="expense">Expense</option><option value="income">Income</option></select><input required className={field} placeholder="Category (feed, veterinary, sale)" value={finance.category} onChange={e=>setFinance({...finance,category:e.target.value})}/><input required type="number" min="0.01" step="0.01" className={field} placeholder="Amount MWK" value={finance.amount} onChange={e=>setFinance({...finance,amount:e.target.value})}/><input required type="date" className={field} value={finance.occurred_on} onChange={e=>setFinance({...finance,occurred_on:e.target.value})}/><textarea className={`${field} sm:col-span-2`} placeholder="Description" value={finance.description} onChange={e=>setFinance({...finance,description:e.target.value})}/><p className="sm:col-span-2 text-sm font-semibold">Income MWK {herd.profitability.income} · Expenses MWK {herd.profitability.expenses} · Net MWK {herd.profitability.net}</p></RecordForm>
 <RecordForm title="Movement or transport trace" icon={<GitBranch/>} onSubmit={e=>void submit(e,`/api/livestock/herds/${id}/movements/`,movement,"Traceability event appended.",()=>setMovement({...movement,location:"",description:""}))}><select className={field} value={movement.event_type} onChange={e=>setMovement({...movement,event_type:e.target.value})}><option value="movement">Movement</option><option value="transport">Transport</option></select><input required className={field} placeholder="Location" value={movement.location} onChange={e=>setMovement({...movement,location:e.target.value})}/><input type="number" min="1" className={field} placeholder={`Quantity (default ${herd.head_count})`} value={movement.quantity} onChange={e=>setMovement({...movement,quantity:e.target.value})}/><textarea required className={`${field} sm:col-span-2`} placeholder="Movement, permit or transport details" value={movement.description} onChange={e=>setMovement({...movement,description:e.target.value})}/></RecordForm>
 </section><section className="rounded-2xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 className="font-bold">Recent records</h2><div className="mt-3 grid gap-4 md:grid-cols-3"><RecordList title="Health" rows={herd.health_events.map(x=>`${x.occurred_on} · ${x.event_type}: ${x.description}`)}/><RecordList title="Production" rows={herd.production_records.map(x=>`${x.recorded_on} · ${x.record_type}: ${x.quantity} ${x.unit}`)}/><RecordList title="Animals" rows={herd.animals.map(x=>`${x.identifier} · ${x.sex}${x.weight_kg?` · ${x.weight_kg} kg`:""}`)}/></div></section>
 </main>;
}
function RecordForm({title,icon,onSubmit,children}:{title:string;icon:ReactNode;onSubmit:(event:FormEvent)=>void;children:ReactNode}){return <form onSubmit={onSubmit} className="rounded-2xl border bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><h2 className="flex items-center gap-2 font-bold">{icon}{title}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{children}</div><button className="mt-4 rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Save record</button></form>}
function RecordList({title,rows}:{title:string;rows:string[]}){return <div><h3 className="font-semibold">{title}</h3>{rows.slice(0,6).map((x,index)=><p className="mt-2 text-sm text-gray-600" key={`${x}-${index}`}>{x}</p>)}{!rows.length&&<p className="mt-2 text-sm text-gray-500">No records yet.</p>}</div>}
