import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { Bird, CalendarClock, HeartPulse, Plus, ShieldCheck } from "lucide-react";
import api, { getApiError } from "../../lib/api";

type Herd = { id:number; name:string; species:string; breed:string; purpose:string; head_count:number; housing:string; status:string };
type Reminder = { id:number; herd_name:string; vaccine_name:string; due_on:string; status:string };
type Advice = { guidance:string[]; source:string; coverage:string; warning:string; urgent_signs:string[] };
const species = ["cattle","goats","sheep","pigs","chickens_broilers","chickens_layers","chickens_indigenous","ducks","rabbits","other"];
const label = (value:string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

export default function LivestockDashboard(){
  const [herds,setHerds]=useState<Herd[]>([]); const [reminders,setReminders]=useState<Reminder[]>([]); const [advice,setAdvice]=useState<Advice|null>(null);
  const [notice,setNotice]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [profile,setProfile]=useState({farm_name:"",production_system:"mixed",district:"",species_kept:[] as string[]});
  const [herd,setHerd]=useState({name:"",species:"chickens_indigenous",breed:"",purpose:"",head_count:"1",housing:""});
  const load=async()=>{try{const [p,h,r,a]=await Promise.all([api.get("/api/livestock/profile/"),api.get<Herd[]>("/api/livestock/herds/"),api.get<Reminder[]>("/api/livestock/reminders/"),api.get<Advice>("/api/livestock/advisory/")]);if(p.data)setProfile({...profile,...p.data});setHerds(h.data);setReminders(r.data);setAdvice(a.data);}catch(reason){setError(getApiError(reason,"Livestock records could not be loaded."));}};
  useEffect(()=>{void load();},[]);
  const saveProfile=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{await api.put("/api/livestock/profile/",profile);setNotice("Livestock farmer profile saved.");}catch(reason){setError(getApiError(reason,"Profile could not be saved."));}finally{setBusy(false);}};
  const addHerd=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{await api.post("/api/livestock/herds/",{...herd,head_count:Number(herd.head_count)});setHerd({...herd,name:"",breed:"",purpose:"",head_count:"1",housing:""});setNotice("Herd or flock added.");await load();}catch(reason){setError(getApiError(reason,"Herd or flock could not be added."));}finally{setBusy(false);}};
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
    <header className="rounded-2xl bg-gradient-to-r from-emerald-900 to-green-700 p-6 text-white"><div className="flex items-center gap-3"><Bird size={32}/><div><h1 className="text-2xl font-bold">Livestock & poultry</h1><p className="mt-1 text-green-100">Manage herds, flocks, health, production, reminders and verified animal sales.</p></div></div></header>
    {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}{notice&&<div role="status" className="rounded-xl border border-green-200 bg-green-50 p-4 text-green-800">{notice}</div>}
    <section className="grid gap-6 lg:grid-cols-2">
      <form onSubmit={saveProfile} className="rounded-2xl border bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><h2 className="text-lg font-bold">Farmer profile</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required className="rounded-lg border p-3 dark:bg-gray-950" placeholder="Farm name" value={profile.farm_name} onChange={e=>setProfile({...profile,farm_name:e.target.value})}/><select className="rounded-lg border p-3 dark:bg-gray-950" value={profile.production_system} onChange={e=>setProfile({...profile,production_system:e.target.value})}>{["mixed","pastoral","intensive","free_range","backyard"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><input className="rounded-lg border p-3 dark:bg-gray-950" placeholder="District" value={profile.district} onChange={e=>setProfile({...profile,district:e.target.value})}/><input className="rounded-lg border p-3 dark:bg-gray-950" placeholder="Species, comma separated" value={profile.species_kept.join(", ")} onChange={e=>setProfile({...profile,species_kept:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></div><button disabled={busy} className="mt-4 rounded-lg bg-green-700 px-4 py-2 font-semibold text-white disabled:opacity-50">Save profile</button></form>
      <form onSubmit={addHerd} className="rounded-2xl border bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><h2 className="text-lg font-bold">Add herd or flock</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required className="rounded-lg border p-3 dark:bg-gray-950" placeholder="Record name" value={herd.name} onChange={e=>setHerd({...herd,name:e.target.value})}/><select className="rounded-lg border p-3 dark:bg-gray-950" value={herd.species} onChange={e=>setHerd({...herd,species:e.target.value})}>{species.map(x=><option key={x} value={x}>{label(x)}</option>)}</select><input className="rounded-lg border p-3 dark:bg-gray-950" placeholder="Breed" value={herd.breed} onChange={e=>setHerd({...herd,breed:e.target.value})}/><input required min="0" type="number" className="rounded-lg border p-3 dark:bg-gray-950" placeholder="Head count" value={herd.head_count} onChange={e=>setHerd({...herd,head_count:e.target.value})}/><input className="rounded-lg border p-3 dark:bg-gray-950" placeholder="Purpose (eggs, milk, breeding)" value={herd.purpose} onChange={e=>setHerd({...herd,purpose:e.target.value})}/><input className="rounded-lg border p-3 dark:bg-gray-950" placeholder="Housing" value={herd.housing} onChange={e=>setHerd({...herd,housing:e.target.value})}/></div><button disabled={busy} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-green-700 px-4 py-2 font-semibold text-white"><Plus size={18}/>Add record</button></form>
    </section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Your herds and flocks</h2><Link to="/app/listings/new" className="text-sm font-semibold text-green-700">Sell animal products</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{herds.map(row=><Link key={row.id} to={`/app/livestock/herds/${row.id}`} className="rounded-xl border p-4 text-left hover:border-green-500"><div className="flex justify-between"><strong>{row.name}</strong><span className="rounded-full bg-green-100 px-2 py-1 text-xs text-green-800">{row.head_count}</span></div><p className="mt-2 text-sm text-gray-600">{label(row.species)}{row.breed?` · ${row.breed}`:""}</p><p className="mt-2 text-xs font-semibold text-green-700">Open complete livestock record</p></Link>)}{!herds.length&&<p className="text-gray-500">No herd or flock records yet.</p>}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 className="flex items-center gap-2 font-bold"><CalendarClock/>Vaccination reminders</h2><div className="mt-3 space-y-2">{reminders.map(x=><div key={x.id} className="rounded-lg bg-gray-50 p-3 dark:bg-gray-950"><strong>{x.vaccine_name}</strong><p className="text-sm">{x.herd_name} · due {x.due_on} · {x.status}</p></div>)}{!reminders.length&&<p className="text-sm text-gray-500">No reminders scheduled. Confirm vaccination timing with a qualified livestock professional.</p>}</div></div>
    <div className="rounded-2xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 className="flex items-center gap-2 font-bold"><HeartPulse/>Safe husbandry guidance</h2>{advice&&<><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{advice.guidance.map(x=><li key={x}>{x}</li>)}</ul><div className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><strong>Important:</strong> {advice.warning}</div><p className="mt-3 flex gap-2 text-xs text-gray-500"><ShieldCheck size={16}/>{advice.source}. {advice.coverage}</p></>}</div></section>
  </main>;
}
