import { useState } from "react";
import { Bell, Mail, Save, Smartphone } from "lucide-react";
import api from "../../lib/api";
import Card from "../../components/ui/Card";
import Button from "../../components/ui/Button";
import AccountNav from "../../components/AccountNav";

const groups = [{ title: "Email", description: "Updates delivered to your email address", icon: Mail, keys: [["emailNewOrders", "Orders and important account activity"], ["emailPriceAlerts", "Price alerts for saved products"], ["emailMessages", "New messages"]] }, { title: "SMS", description: "Useful updates sent to your mobile number", icon: Smartphone, keys: [["smsNewOrders", "Orders and important account activity"], ["smsPriceAlerts", "Price alerts for saved products"], ["smsMessages", "New messages"]] }, { title: "Push notifications", description: "Alerts sent to your device when the app is installed", icon: Bell, keys: [["pushNewOrders", "Orders and important account activity"], ["pushPriceAlerts", "Price alerts for saved products"], ["pushMessages", "New messages"]] }];
export default function NotificationSettings() { const [settings, setSettings] = useState<Record<string, boolean>>({ emailNewOrders: true, emailPriceAlerts: true, emailMessages: true, smsNewOrders: false, smsPriceAlerts: false, smsMessages: true, pushNewOrders: true, pushPriceAlerts: true, pushMessages: true }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const save = async () => { setSaving(true); setMessage(""); try { await api.put("/api/users/notifications", settings); setMessage("Notification preferences saved."); } catch { setMessage("We could not save your preferences. Please try again."); } finally { setSaving(false); } };
return <div className="mx-auto max-w-6xl"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-[.15em] text-green-700">My account</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight dark:text-white">Notification preferences</h1><p className="mt-2 text-slate-500">Choose how you want to hear about your activity.</p></div><div className="grid gap-7 lg:grid-cols-[240px_1fr]"><Card className="h-fit p-3"><AccountNav /></Card><div className="space-y-4">{groups.map(group => <Card key={group.title} className="p-6"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-green-50 text-green-700 dark:bg-green-950/30"><group.icon size={20} /></span><div><h2 className="font-extrabold dark:text-white">{group.title}</h2><p className="mt-1 text-sm text-slate-500">{group.description}</p></div></div><div className="mt-5 divide-y divide-slate-100 border-t border-slate-100 dark:divide-gray-800 dark:border-gray-800">{group.keys.map(([key, label]) => <label key={key} className="flex cursor-pointer items-center justify-between gap-4 py-4 text-sm font-medium"><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={() => setSettings(current => ({ ...current, [key]: !current[key] }))} className="h-5 w-5 rounded border-slate-300 text-green-700 focus:ring-green-600" /></label>)}</div></Card>)}<div className="sticky bottom-4 flex items-center justify-between rounded-xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur dark:border-gray-800 dark:bg-gray-900/95"><p role="status" className={`text-sm ${message.includes("could not") ? "text-red-600" : "text-green-700"}`}>{message}</p><Button onClick={save} disabled={saving}><Save size={17} className="mr-2" />{saving ? "Saving..." : "Save changes"}</Button></div></div></div></div>; }
