import{expect,test,type APIRequestContext}from"@playwright/test";import{createHmac}from"node:crypto";import{readdirSync,readFileSync}from"node:fs";import{resolve}from"node:path";
const api="http://127.0.0.1:8000";
async function csrf(client:APIRequestContext){const response=await client.get(`${api}/api/v1/csrf/`);return(await response.json()).csrfToken as string;}
async function post(client:APIRequestContext,path:string,data:unknown){return client.post(`${api}/api/v1${path}`,{data,headers:{"X-CSRFToken":await csrf(client)}});}
async function patch(client:APIRequestContext,path:string,data:unknown){return client.patch(`${api}/api/v1${path}`,{data,headers:{"X-CSRFToken":await csrf(client)}});}
async function verificationCode(email:string){for(let tries=0;tries<30;tries++){for(const name of readdirSync(resolve(".e2e/emails"))){const body=readFileSync(resolve(".e2e/emails",name),"utf8");if(body.includes(email)){const match=body.match(/verification code is (\d{6})/);if(match)return match[1];}}await new Promise(done=>setTimeout(done,200));}throw new Error(`Verification email for ${email} was not written`);}
async function registerAndVerify(client:APIRequestContext,username:string,email:string,mode:"sell"|"buy"){const registration=await post(client,"/auth/register/",{username,email,password:"StrongPass!234",phone:"",user_type:mode==="sell"?"farmer":"buyer",account_type:"individual",trading_mode:mode});expect(registration.status(),await registration.text()).toBe(201);const verification=await post(client,"/auth/verify-otp/",{email,otp:await verificationCode(email)});expect(verification.ok()).toBeTruthy();const login=await post(client,"/auth/login/",{identifier:email,password:"StrongPass!234"});expect(login.ok()).toBeTruthy();return(await login.json()).user.id as number;}
test("registration, verification, listing, checkout, webhook, fulfilment and dispute resolution",async({playwright,page})=>{const seller=await playwright.request.newContext(),buyer=await playwright.request.newContext(),admin=await playwright.request.newContext(),transporter=await playwright.request.newContext();await registerAndVerify(seller,"e2e_seller","seller@e2e.test","sell");await registerAndVerify(buyer,"e2e_buyer","buyer@e2e.test","buy");await post(admin,"/auth/login/",{identifier:"admin@e2e.test",password:"AdminPass!234"});const transporterLogin=await post(transporter,"/auth/login/",{identifier:"transport@e2e.test",password:"TransportPass!234"});const transporterId=(await transporterLogin.json()).user.id;
const listingResponse=await post(seller,"/marketplace/listings/",{name:"E2E Groundnuts",description:"Traceable test harvest",price:"2500",quantity:20,category:"produce",listing_type:"fixed-price",condition:"new",unit:"kg",pack_size:"1",minimum_order:1,allow_partial_fulfilment:true});expect(listingResponse.status()).toBe(201);const listing=await listingResponse.json();expect((await post(admin,"/admin/listings/approvals/",{listing_id:listing.id,decision:"approved",reason:"Automated browser acceptance"})).ok()).toBeTruthy();
const checkout=await post(buyer,"/payments/checkout-sessions/",{payment_method:"bank_transfer",items:[{product_id:listing.id,quantity:2}]});expect(checkout.status()).toBe(201);const order=(await checkout.json()).order;expect((await patch(admin,`/marketplace/orders/${order.id}/status/`,{status:"paid"})).ok()).toBeTruthy();expect((await post(admin,"/admin/deliveries/",{order_id:order.id,transporter_id:transporterId,pickup_location:"Lilongwe",delivery_location:"Blantyre",reason:"E2E delivery assignment"})).ok()).toBeTruthy();
const body=JSON.stringify({event:"payment.confirmed",order_id:order.id});const webhook=await admin.post(`${api}/api/v1/payments/webhooks/e2e/`,{data:body,headers:{"Content-Type":"application/json","X-Webhook-Signature":createHmac("sha256","e2e-webhook-secret").update(body).digest("hex")}});expect(webhook.ok()).toBeTruthy();for(const status of["accepted","packed","dispatched"])expect((await patch(seller,`/marketplace/orders/${order.id}/status/`,{status})).ok()).toBeTruthy();
const evidence=await transporter.post(`${api}/api/v1/marketplace/orders/${order.id}/delivery-evidence/`,{multipart:{evidence_type:"delivery",signature_name:"E2E Buyer",file:{name:"delivery.jpg",mimeType:"image/jpeg",buffer:Buffer.from([0xff,0xd8,0xff,0xd9])}},headers:{"X-CSRFToken":await csrf(transporter)}});expect(evidence.status()).toBe(201);expect((await patch(transporter,`/marketplace/orders/${order.id}/status/`,{status:"delivered"})).ok()).toBeTruthy();
const dispute=await post(buyer,`/marketplace/orders/${order.id}/dispute/`,{reason:"Delivered goods were damaged during the automated test",evidence:["e2e-photo-reference"]});expect(dispute.status()).toBe(201);const disputeId=(await dispute.json()).id;expect((await post(admin,`/admin/disputes/${disputeId}/decision/`,{decision:"reject",note:"Evidence reviewed in automated end-to-end test."})).ok()).toBeTruthy();await page.goto("/login");await expect(page.getByRole("heading",{name:/welcome back/i})).toBeVisible();for(const context of[seller,buyer,admin,transporter])await context.dispose();});
