import { useState } from "react";
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, BarChart3, Bird, Check, ChevronDown, Leaf, Menu, MessageCircle, PackageCheck, ShieldCheck, ShoppingBasket, Smartphone, Sprout, Truck, Users, X } from "lucide-react";
import InstallAppButton from "../components/InstallAppButton";
import ThemeToggle from "../components/ThemeToggle";

const primary = "inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white shadow-lg transition hover:bg-emerald-800 focus:outline-none focus:ring-4 focus:ring-emerald-300";
const secondary = "inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border-2 border-emerald-700 bg-white px-6 py-3 font-bold text-emerald-800 transition hover:bg-emerald-50 focus:outline-none focus:ring-4 focus:ring-emerald-200 dark:bg-transparent dark:text-emerald-300";

const audiences = [
  { icon: Sprout, title: "Farmers", text: "List crops and animal products, follow orders, compare market information and keep farm records.", action: "Register as a farmer" },
  { icon: ShoppingBasket, title: "Buyers", text: "Find agricultural products by location, quantity, availability and verification status.", action: "Register as a buyer" },
  { icon: Truck, title: "Transporters", text: "Create a verified profile, quote for deliveries and record pickup and delivery evidence.", action: "Join as a transporter" },
  { icon: Users, title: "Cooperatives & teams", text: "Manage members, delegated roles, shared listings, approvals and organisation reporting.", action: "Create an organisation" },
];

const capabilities = [
  { icon: ShoppingBasket, title: "One agricultural marketplace", text: "Crops, eggs, milk, feed, manure, livestock and poultry with agricultural units and availability details." },
  { icon: BarChart3, title: "Useful decision support", text: "Weather, historical market prices and responsible advisory show their source, coverage and freshness." },
  { icon: PackageCheck, title: "Traceable fulfilment", text: "Order status, delivery evidence and integrity-checked batch events make important steps easier to follow." },
  { icon: ShieldCheck, title: "Safer transactions", text: "Verified profiles, audited administration, disputes and payment reconciliation support accountable trade." },
  { icon: Bird, title: "Crops, livestock & poultry", text: "Keep herd or flock records, health events, production records, reminders and welfare-aware transport details." },
  { icon: Smartphone, title: "Built for Malawi", text: "Responsive screens, low-data options, installable web access, email, SMS and growing Chichewa support." },
];

const faqs = [
  ["Is registration free?", "Yes. You can create an account without paying. Any transaction or subscription charge must be shown before you confirm it."],
  ["Do I need a smartphone?", "The web platform works on phones and computers. Selected services are also being prepared for low-data and USSD access."],
  ["Are payments and providers always available?", "Availability depends on the provider and current platform readiness. An incomplete payment is never presented as successful."],
  ["Is agricultural advice a confirmed diagnosis?", "No. Automated guidance is decision support. Urgent crop or animal-health cases should be escalated to a qualified professional."],
];

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="min-h-screen bg-white text-slate-950 dark:bg-slate-950 dark:text-white">
    <Helmet>
      <title>MlimiConnect | Malawi's connected agricultural marketplace</title>
      <meta name="description" content="Buy, sell, transport and manage crops, livestock and poultry through one Malawi-focused agricultural platform. Create a free MlimiConnect account." />
      <meta property="og:title" content="MlimiConnect | Agriculture, connected" />
      <meta property="og:description" content="A practical platform for Malawi's farmers, buyers, transporters and agricultural organisations." />
    </Helmet>
    <a href="#main-content" className="sr-only z-[100] rounded bg-white p-3 text-emerald-800 focus:not-sr-only focus:fixed focus:left-3 focus:top-3">Skip to main content</a>
    <header className="sticky top-0 z-50 border-b border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950">
      <nav aria-label="Main navigation" className="mx-auto flex max-w-7xl items-center justify-between gap-2 px-3 py-2.5 sm:px-6 sm:py-3">
        <Link to="/" className="flex min-w-0 shrink items-center gap-2" aria-label="MlimiConnect home"><img src="/logo-mark.png" alt="" className="h-10 w-10 shrink-0" /><span className="hidden whitespace-nowrap text-xl font-black min-[390px]:inline">Mlimi<span className="text-emerald-700 dark:text-emerald-400">Connect</span></span></Link>
        <div className="hidden items-center gap-6 text-sm font-semibold lg:flex"><a href="#who" className="hover:text-emerald-700">Who it is for</a><a href="#features" className="hover:text-emerald-700">What you can do</a><Link to="/app/marketplace" className="hover:text-emerald-700">Marketplace</Link><Link to="/about" className="hover:text-emerald-700">About</Link><Link to="/support" className="hover:text-emerald-700">Help</Link></div>
        <div className="flex shrink-0 items-center gap-1 sm:gap-2"><span className="hidden min-[340px]:inline-flex"><InstallAppButton compact /></span><ThemeToggle /><Link to="/login" className="hidden min-h-10 items-center rounded-lg px-2.5 py-2 font-semibold hover:bg-slate-100 sm:inline-flex dark:hover:bg-slate-800">Sign in</Link><Link to="/register" className={`${primary} hidden min-h-10 px-3 py-2 text-sm sm:inline-flex md:px-4`}>Create free account</Link><button type="button" aria-expanded={menuOpen} aria-controls="mobile-menu" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(v => !v)} className="inline-flex h-10 w-10 items-center justify-center rounded-lg hover:bg-slate-100 lg:hidden dark:hover:bg-slate-800">{menuOpen ? <X /> : <Menu />}</button></div>
      </nav>
      {menuOpen && <div id="mobile-menu" className="absolute inset-x-0 top-full max-h-[calc(100vh-4rem)] overflow-y-auto border-t border-slate-200 bg-white px-3 py-3 shadow-xl lg:hidden dark:border-slate-800 dark:bg-slate-950"><div className="mx-auto grid max-w-7xl gap-1"><a href="#who" onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-2.5 hover:bg-slate-100 dark:hover:bg-slate-900">Who it is for</a><a href="#features" onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-2.5 hover:bg-slate-100 dark:hover:bg-slate-900">What you can do</a><Link to="/app/marketplace" onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-2.5 hover:bg-slate-100 dark:hover:bg-slate-900">Marketplace</Link><Link to="/about" onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-2.5 hover:bg-slate-100 dark:hover:bg-slate-900">About</Link><Link to="/support" onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-2.5 hover:bg-slate-100 dark:hover:bg-slate-900">Help</Link><div className="mt-2 grid grid-cols-1 gap-2 min-[400px]:grid-cols-2"><Link to="/login" onClick={() => setMenuOpen(false)} className={`${secondary} min-h-11 px-3 py-2`}>Sign in</Link><Link to="/register" onClick={() => setMenuOpen(false)} className={`${primary} min-h-11 px-3 py-2 text-center text-sm`}>Create account</Link></div></div></div>}
    </header>

    <main id="main-content">
      <section className="relative isolate overflow-hidden bg-emerald-950 text-white">
        <img src="/hero.png" alt="A green farm field in Malawi" className="absolute inset-0 -z-20 h-full w-full object-cover" fetchPriority="high" />
        <div className="absolute inset-0 -z-10 bg-gradient-to-r from-emerald-950 via-emerald-950/95 to-emerald-950/35" />
        <div className="mx-auto grid min-h-[570px] max-w-7xl items-center px-4 py-12 sm:min-h-[660px] sm:px-6 sm:py-20 lg:grid-cols-[1.1fr_.9fr]">
          <div className="max-w-3xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-300/30 bg-emerald-900/70 px-4 py-2 text-sm font-bold text-emerald-100"><Leaf size={17} /> Crops, livestock and poultry—connected</p><h1 className="text-4xl font-black leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">Grow your market.<br/><span className="text-amber-300">Trade with confidence.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-50 sm:text-xl">MlimiConnect brings farmers, buyers, transporters and agricultural organisations together—from listing and discovery to delivery records, market information and farm management.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/register" className={`${primary} bg-amber-400 text-emerald-950 hover:bg-amber-300`}>Create your free account <ArrowRight size={19}/></Link><Link to="/app/marketplace" className={`${secondary} border-white/70 bg-white/10 text-white hover:bg-white/20`}>Explore the marketplace</Link></div><ul className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm text-emerald-50"><li className="flex gap-2"><Check size={18} className="text-amber-300"/>No card required to register</li><li className="flex gap-2"><Check size={18} className="text-amber-300"/>Malawi-focused</li><li className="flex gap-2"><Check size={18} className="text-amber-300"/>Built for low-data access</li></ul></div>
          <div className="mt-12 hidden justify-end lg:flex"><div className="w-full max-w-lg rounded-3xl border border-white/20 bg-white/10 p-4 shadow-2xl backdrop-blur"><img src="/dashboard-screenshot.png" alt="Preview of the MlimiConnect dashboard" className="w-full rounded-2xl" /><div className="grid grid-cols-3 gap-2 pt-4 text-center text-xs font-bold"><span className="rounded-xl bg-white/10 p-3">Marketplace</span><span className="rounded-xl bg-white/10 p-3">Farm records</span><span className="rounded-xl bg-white/10 p-3">Deliveries</span></div></div></div>
        </div>
      </section>

      <section aria-label="Trust statement" className="border-b bg-amber-50 py-5 text-amber-950 dark:border-slate-800 dark:bg-amber-950/25 dark:text-amber-100"><div className="mx-auto flex max-w-7xl flex-col items-center justify-center gap-3 px-4 text-center sm:flex-row sm:gap-8"><span className="flex items-center gap-2 font-bold"><BadgeCheck className="text-emerald-700"/>Registered Malawi business</span><span className="hidden sm:block">•</span><span>Clear provider status and source attribution</span><span className="hidden sm:block">•</span><span>Privacy and consent controls</span></div></section>

      <section id="who" className="py-12 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-widest text-emerald-700 dark:text-emerald-400 sm:text-base">Made for the whole value chain</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">One platform. A clear place for you.</h2><p className="mt-3 text-base text-slate-600 dark:text-slate-300 sm:mt-4 sm:text-lg">Choose the account that matches the work you do. You can add organisation and team access as you grow.</p></div><div className="mt-7 grid gap-3 sm:mt-10 sm:gap-5 md:grid-cols-2 lg:grid-cols-4">{audiences.map(({icon: Icon,title,text,action}) => <article key={title} className="group rounded-xl border border-slate-200 bg-white p-4 transition hover:border-emerald-400 sm:rounded-2xl sm:p-6 sm:shadow-sm sm:hover:-translate-y-1 sm:hover:shadow-xl dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3 sm:block"><Icon className="shrink-0 text-emerald-700 dark:text-emerald-400" size={28}/><h3 className="text-lg font-black sm:mt-5 sm:text-xl">{title}</h3></div><p className="mt-2 text-sm leading-6 text-slate-600 sm:mt-3 sm:min-h-24 sm:text-base sm:leading-7 dark:text-slate-300">{text}</p><Link to="/register" className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-emerald-700 sm:mt-5 sm:text-base dark:text-emerald-400">{action}<ArrowRight size={17}/></Link></article>)}</div></div></section>

      <section id="features" className="bg-slate-50 py-12 dark:bg-slate-900/60 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-emerald-700 dark:text-emerald-400 sm:text-base">Practical tools, connected</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">From the farm gate to the buyer</h2><p className="mx-auto mt-3 max-w-3xl text-base text-slate-600 dark:text-slate-300 sm:mt-4 sm:text-lg">Start with one useful workflow today and add more as your farm, business or cooperative grows.</p></div><div className="mt-7 grid gap-3 sm:mt-12 sm:gap-5 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(({icon: Icon,title,text}) => <article key={title} className="rounded-xl border border-slate-200 bg-white p-4 sm:rounded-2xl sm:p-7 dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center gap-3 sm:block"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-emerald-100 text-emerald-800 sm:h-12 sm:w-12 sm:rounded-xl dark:bg-emerald-950 dark:text-emerald-300"><Icon size={21}/></div><h3 className="text-lg font-black sm:mt-5 sm:text-xl">{title}</h3></div><p className="mt-2 text-sm leading-6 text-slate-600 sm:mt-3 sm:text-base sm:leading-7 dark:text-slate-300">{text}</p></article>)}</div></div></section>

      <section className="py-20 sm:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2"><div><p className="font-bold uppercase tracking-widest text-emerald-700 dark:text-emerald-400">Simple to begin</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Your first step takes only a few minutes</h2><div className="mt-8 space-y-6">{[["Create your account","Choose your role and verify your contact details."],["Complete your profile","Add your location, organisation or trading information."],["Start with what you need","Browse, list, request transport, check advisory or manage farm records."]].map(([title,text], index) => <div className="flex gap-4" key={title}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-emerald-700 font-black text-white">{index+1}</span><div><h3 className="text-lg font-black">{title}</h3><p className="mt-1 text-slate-600 dark:text-slate-300">{text}</p></div></div>)}</div><Link to="/register" className={`${primary} mt-9`}>Choose your account type <ArrowRight size={18}/></Link></div><div className="overflow-hidden rounded-3xl bg-emerald-950 p-3 shadow-2xl"><img src="/cta-farm.png" alt="A farmer working in a cultivated field" className="aspect-[4/3] w-full rounded-2xl object-cover" loading="lazy"/></div></div></section>

      <section className="bg-emerald-950 py-20 text-white"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="text-center"><MessageCircle className="mx-auto text-amber-300" size={38}/><h2 className="mt-4 text-3xl font-black sm:text-4xl">Know what to expect</h2><p className="mt-3 text-emerald-100">Clear answers before you create an account.</p></div><div className="mt-9 grid gap-3">{faqs.map(([question,answer]) => <details key={question} className="group rounded-xl border border-white/15 bg-white/5 p-5"><summary className="flex cursor-pointer list-none items-center justify-between font-bold">{question}<ChevronDown className="transition group-open:rotate-180"/></summary><p className="mt-4 max-w-3xl leading-7 text-emerald-100">{answer}</p></details>)}</div></div></section>
      <section className="bg-amber-300 py-16 text-emerald-950"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-7 px-4 text-center sm:px-6 lg:flex-row lg:text-left"><div><h2 className="text-3xl font-black sm:text-4xl">Ready to connect your agricultural work?</h2><p className="mt-2 text-lg font-medium">Create your free account and start with the tools that matter to you.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link to="/register" className={`${primary} bg-emerald-950 hover:bg-emerald-900`}>Get started free <ArrowRight/></Link><Link to="/support" className="inline-flex min-h-12 items-center justify-center rounded-xl border-2 border-emerald-950 px-6 py-3 font-bold">Ask a question</Link></div></div></section>
    </main>
    <footer className="bg-slate-950 py-12 text-slate-300"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 md:grid-cols-[1.5fr_1fr_1fr]"><div><div className="flex items-center gap-2 text-white"><img src="/logo-mark.png" alt="" className="h-10 w-10"/><span className="text-xl font-black">MlimiConnect</span></div><p className="mt-4 max-w-md leading-7">A Malawi-focused agricultural marketplace and farm-management platform for crops, livestock and poultry.</p></div><div><h2 className="font-bold text-white">Platform</h2><div className="mt-4 grid gap-3"><Link to="/app/marketplace">Marketplace</Link><Link to="/pricing">Pricing</Link><Link to="/about">About</Link><Link to="/register">Register</Link></div></div><div><h2 className="font-bold text-white">Trust & support</h2><div className="mt-4 grid gap-3"><Link to="/support">Help centre</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/contact">Contact</Link></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-slate-800 px-4 pt-6 text-sm sm:px-6">© {new Date().getFullYear()} MlimiConnect. Provider-dependent services are shown according to current availability.</div></footer>
  </div>;
}
