import { useState } from "react";
import type { FormEvent } from "react";
import { CheckCircle, MapPin, Search } from "lucide-react";
import api, { getApiError } from "../lib/api";
import Button from "./ui/Button";

export type AddressSelection = { label:string; latitude:string; longitude:string; osm_reference:string; selection_token:string };
type SearchResponse = { results:AddressSelection[]; cached:boolean; attribution:string; attribution_url:string; notice:string };

export default function AddressSearch({label,onSelect}:{label:string;onSelect:(selection:AddressSelection|null)=>void}){
  const[query,setQuery]=useState(""),[results,setResults]=useState<AddressSelection[]>([]),[selected,setSelected]=useState<AddressSelection|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[attribution,setAttribution]=useState("© OpenStreetMap contributors");
  const search=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setError("");try{const response=await api.get<SearchResponse>("/api/locations/search/",{params:{q:query}});setResults(response.data.results);setAttribution(response.data.attribution);if(!response.data.results.length)setError("No matching Malawi location was found. Try a nearby landmark, trading centre, village or district.");}catch(e){setError(getApiError(e,"Address search is temporarily unavailable."));}finally{setLoading(false);}};
  const choose=(row:AddressSelection)=>{setSelected(row);setQuery(row.label);setResults([]);onSelect(row);};
  return <fieldset className="rounded-lg border p-4"><legend className="px-2 font-bold">{label}</legend><form onSubmit={search} className="flex gap-2"><input value={query} onChange={event=>{setQuery(event.target.value);setSelected(null);onSelect(null);}} required minLength={3} maxLength={160} placeholder="Village, road, trading centre or landmark" className="min-w-0 flex-1 rounded border p-3 dark:bg-slate-900"/><Button type="submit" variant="outline" disabled={loading}><Search className="mr-2" size={17}/>{loading?"Searching…":"Search"}</Button></form><p className="mt-2 text-xs text-slate-500">Search happens only when you press Search. Do not enter a person’s name, phone number or other confidential information.</p>{error&&<p role="alert" className="mt-3 text-sm text-amber-800">{error}</p>}{results.length>0&&<ul className="mt-3 space-y-2">{results.map(row=><li key={row.selection_token}><button type="button" onClick={()=>choose(row)} className="w-full rounded-lg border p-3 text-left hover:border-green-600"><MapPin className="mr-2 inline text-green-700" size={17}/>{row.label}<span className="mt-1 block text-xs text-slate-500">{row.latitude}, {row.longitude}</span></button></li>)}</ul>}{selected&&<p role="status" className="mt-3 text-sm font-semibold text-green-700"><CheckCircle className="mr-1 inline" size={17}/>Confirmed: {selected.label}</p>}<p className="mt-3 text-xs"><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer" className="underline">{attribution}</a></p></fieldset>;
}
