import { type ReactNode } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, Leaf } from "lucide-react";

export default function AuthShell({ children, title, description }: { children: ReactNode; title: string; description: string }) {
  return <div className="min-h-screen bg-slate-100 p-3 sm:p-6 dark:bg-gray-950"><div className="mx-auto grid min-h-[calc(100vh-1.5rem)] max-w-7xl overflow-hidden rounded-2xl bg-white shadow-2xl shadow-slate-900/10 lg:grid-cols-[.9fr_1.1fr] dark:bg-gray-900 sm:min-h-[calc(100vh-3rem)]">
    <aside className="relative hidden overflow-hidden bg-slate-950 p-10 text-white lg:flex lg:flex-col"><div className="absolute inset-0 bg-[url('/hero.png')] bg-cover bg-center opacity-20" /><div className="absolute inset-0 bg-gradient-to-br from-green-900/90 via-slate-950/95 to-slate-950" /><Link to="/" className="relative z-10 flex items-center gap-2 text-xl font-extrabold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-green-600"><Leaf size={23} /></span>Mlimi<span className="text-green-400">Connect</span></Link><div className="relative z-10 my-auto"><p className="text-sm font-bold uppercase tracking-[.18em] text-amber-300">Malawi's trusted farm market</p><h2 className="mt-4 max-w-sm text-4xl font-extrabold leading-tight">Trade better. Grow further.</h2><p className="mt-5 max-w-sm text-slate-300">A professional marketplace for farmers, buyers and agricultural businesses.</p><div className="mt-9 space-y-4 text-sm text-slate-200"><p className="flex items-center gap-3"><CheckCircle2 className="text-green-400" size={19} /> Direct access to quality produce</p><p className="flex items-center gap-3"><CheckCircle2 className="text-green-400" size={19} /> Transparent prices and secure orders</p><p className="flex items-center gap-3"><CheckCircle2 className="text-green-400" size={19} /> Built for Malawi's agricultural community</p></div></div><p className="relative z-10 text-sm text-slate-400">© {new Date().getFullYear()} MlimiConnect</p></aside>
    <main className="flex items-center justify-center px-5 py-10 sm:px-10"><div className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center gap-2 text-lg font-extrabold text-slate-900 lg:hidden dark:text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-green-700 text-white"><Leaf size={20} /></span>Mlimi<span className="text-green-700">Connect</span></Link><div className="mb-8"><p className="text-sm font-bold uppercase tracking-[.15em] text-green-700">Secure account access</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">{title}</h1><p className="mt-2 text-slate-500 dark:text-gray-400">{description}</p></div>{children}</div></main>
  </div></div>;
}
