import { useEffect, useMemo, useState } from "react";
import { Download, Leaf, QrCode, Search, ShieldCheck, X } from "lucide-react";
import { QRCodeCanvas } from "qrcode.react";
import { Link } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import api, { getApiError } from "../../lib/api";
import { publicTraceabilityUrl } from "../../lib/traceability";
import Button from "../../components/ui/Button";
import Card from "../../components/ui/Card";

type Batch = { id: number; batch_code: string; product: string; quantity: string; status: string; created_at: string; updated_at: string; events: Array<{id:number}>; integrity: { valid: boolean; event_count: number } };

export default function TraceabilityOverview() {
  const { user } = useAuth();
  const isFarmer = user?.can_sell === true || user?.user_type === "farmer";
  const [batches, setBatches] = useState<Batch[]>([]);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Batch | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => { let active = true; api.get<Batch[] | {results: Batch[]}>("/api/traceability/batches/").then(({data}) => { if (active) setBatches(Array.isArray(data) ? data : data.results); }).catch(e => { if (active) setError(getApiError(e, "Traceability batches could not be loaded.")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? batches.filter(item => `${item.product} ${item.batch_code} ${item.status}`.toLowerCase().includes(needle)) : batches; }, [batches, query]);
  const downloadQr = () => { if (!selected) return; const canvas = document.getElementById("batch-qr") as HTMLCanvasElement | null; if (!canvas) return; const link = document.createElement("a"); link.href = canvas.toDataURL("image/png"); link.download = `${selected.batch_code}-qr.png`; link.click(); };

  return <main className="min-h-screen bg-slate-50 px-4 py-8 dark:bg-slate-950 sm:px-6"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="flex items-center gap-3 text-3xl font-black"><ShieldCheck className="text-emerald-700"/>Traceability batches</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Persisted, integrity-checked records from registration through movement and delivery.</p></div>{isFarmer && <Link to="/app/traceability/batch/new"><Button><Leaf className="mr-2" size={17}/>Register new batch</Button></Link>}</header>
    <Card className="mt-7 p-4"><label className="sr-only" htmlFor="batch-search">Search traceability batches</label><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input id="batch-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by product, batch code or status" className="w-full rounded-lg border border-slate-300 bg-white py-3 pl-11 pr-4 dark:border-slate-700 dark:bg-slate-900"/></div></Card>
    {error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{error} <button className="ml-2 font-bold underline" onClick={() => window.location.reload()}>Try again</button></p>}
    {loading ? <div role="status" className="mt-8 grid gap-4" aria-label="Loading traceability batches">{[1,2,3].map(i => <div key={i} className="h-28 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/>)}</div> : !error && filtered.length === 0 ? <Card className="mt-8 p-12 text-center"><QrCode className="mx-auto text-slate-400" size={54}/><h2 className="mt-4 text-xl font-bold">{query ? "No matching batches" : "No traceability batches yet"}</h2><p className="mt-2 text-slate-600 dark:text-slate-300">{query ? "Try another product name or batch code." : isFarmer ? "Register your first batch to begin its event history." : "Ask the producer for a public batch code to verify."}</p>{isFarmer && !query && <Link to="/app/traceability/batch/new" className={`${"mt-5 inline-flex rounded-lg bg-emerald-700 px-5 py-3 font-bold text-white"}`}>Register a batch</Link>}</Card> : <div className="mt-7 grid gap-4">{filtered.map(batch => <Card key={batch.id} className="p-5"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-950"><Leaf/></div><div><h2 className="text-lg font-black">{batch.product}</h2><p className="mt-1 text-sm text-slate-500">{batch.batch_code} · {batch.quantity}</p><p className="mt-2 text-sm"><span className={batch.integrity.valid ? "font-bold text-emerald-700" : "font-bold text-red-700"}>{batch.integrity.valid ? "Integrity verified" : "Integrity review required"}</span> · {batch.integrity.event_count} events · {batch.status}</p></div></div><div className="flex flex-wrap gap-2"><Link to={`/app/traceability/batch/${batch.id}`} className="inline-flex min-h-10 items-center rounded-lg border border-emerald-700 px-4 py-2 font-bold text-emerald-700">View history</Link><Button size="sm" onClick={() => setSelected(batch)}><QrCode className="mr-2" size={16}/>QR code</Button></div></div></Card>)}</div>}
    <Card className="mt-10 bg-emerald-50 p-8 text-center dark:bg-emerald-950/30"><QrCode className="mx-auto text-emerald-700" size={48}/><h2 className="mt-3 text-2xl font-black">Verify a public batch</h2><p className="mx-auto mt-2 max-w-2xl text-slate-600 dark:text-slate-300">Scan a packaging QR code or enter its batch code to see the public, integrity-checked journey.</p><Link to="/app/traceability/verify" className="mt-5 inline-flex rounded-lg bg-emerald-700 px-5 py-3 font-bold text-white">Verify now</Link></Card>
  </div>{selected && <div role="dialog" aria-modal="true" aria-labelledby="qr-title" className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className="w-full max-w-sm rounded-2xl bg-white p-7 text-slate-950"><div className="flex justify-between"><div><h2 id="qr-title" className="text-xl font-black">{selected.product}</h2><p className="text-sm text-slate-500">{selected.batch_code}</p></div><button aria-label="Close QR code" onClick={() => setSelected(null)}><X/></button></div><div className="mt-5 flex justify-center"><QRCodeCanvas id="batch-qr" value={publicTraceabilityUrl(selected.batch_code)} size={240}/></div><Button className="mt-6 w-full" onClick={downloadQr}><Download className="mr-2" size={17}/>Download QR code</Button></div></div>}</main>;
}
