import { useEffect, useState } from "react";
import { BarChart3, DollarSign, Package, ShoppingCart, Users } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import Card from "../../components/ui/Card";
import api from "../../lib/api";

type AnalyticsData = { users: number; activeListings: number; orders: number; volume: number; disputes: number; revenueTrend: { period: string; value: number; orders: number }[]; categories: { category: string; value: number }[] };
const demo: AnalyticsData = { users: 2341, activeListings: 4892, orders: 1673, volume: 12800000, disputes: 7, revenueTrend: [{ period: "2026-01-01", value: 5600000, orders: 620 }, { period: "2026-02-01", value: 7100000, orders: 810 }, { period: "2026-03-01", value: 8400000, orders: 940 }, { period: "2026-04-01", value: 9800000, orders: 1080 }, { period: "2026-05-01", value: 11200000, orders: 1320 }, { period: "2026-06-01", value: 12800000, orders: 1673 }], categories: [{ category: "Produce", value: 2840 }, { category: "Seeds", value: 810 }, { category: "Inputs", value: 640 }, { category: "Equipment", value: 602 }] };

export default function Analytics() {
  const demoEnabled = import.meta.env.VITE_DEMO_DATA_ENABLED === "true";
  const [data, setData] = useState<AnalyticsData | null>(demoEnabled ? demo : null);
  const [error, setError] = useState("");
  useEffect(() => { if (demoEnabled) return; api.get<AnalyticsData>("/api/admin/overview/").then(({ data }) => setData({ ...data, volume: Number(data.volume), revenueTrend: data.revenueTrend.map(row => ({ ...row, value: Number(row.value) })) })).catch(() => setError("Platform analytics are temporarily unavailable.")); }, [demoEnabled]);
  if (!data) return <div className="p-8 text-center">{error || "Loading analytics…"}</div>;
  const stats = [{ label: "Transaction volume", value: `MWK ${data.volume.toLocaleString()}`, icon: DollarSign }, { label: "Registered users", value: data.users.toLocaleString(), icon: Users }, { label: "Active listings", value: data.activeListings.toLocaleString(), icon: Package }, { label: "Orders", value: data.orders.toLocaleString(), icon: ShoppingCart }];
  return <div className="mx-auto max-w-7xl py-4 sm:py-8"><div className="mb-6"><h1 className="flex items-center gap-3 text-3xl font-bold"><BarChart3 className="text-green-700" /> Platform analytics</h1><p className="mt-1 text-slate-500">{demoEnabled ? "Demonstration dataset with realistic monthly trends" : "Aggregated from marketplace users, listings and orders"}</p></div>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}<div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(item => <Card key={item.label} className="p-4"><item.icon className="text-green-700" size={22} /><p className="mt-3 text-xs text-slate-500">{item.label}</p><p className="mt-1 text-xl font-black sm:text-2xl">{item.value}</p></Card>)}</div><div className="grid gap-5 lg:grid-cols-2"><Card className="p-4 sm:p-6"><h2 className="mb-4 text-lg font-bold">Revenue and order trend</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.revenueTrend}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="period" tickFormatter={value => new Date(value).toLocaleDateString(undefined, { month: "short" })} /><YAxis width={50} /><Tooltip formatter={value => Number(value).toLocaleString()} /><Line type="monotone" dataKey="value" stroke="#15803d" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="orders" stroke="#f59e0b" strokeWidth={2} /></LineChart></ResponsiveContainer></div></Card><Card className="p-4 sm:p-6"><h2 className="mb-4 text-lg font-bold">Listings by category</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.categories}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="category" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#15803d" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></Card></div></div>;
}
