-keepattributes SourceFile,LineNumberTable,InnerClasses,EnclosingMethod
-renamesourcefileattribute SourceFile
-keep @com.getcapacitor.annotation.CapacitorPlugin public class * { *; }
-keep @com.getcapacitor.annotation.PluginMethod public method *;
-keep class com.getcapacitor.** { *; }
-dontwarn com.getcapacitor.**
-keep class io.sentry.** { *; }
-dontwarn io.sentry.**
-keep class com.aparajita.capacitor.securestorage.** { *; }
-dontwarn com.aparajita.capacitor.securestorage.**
-keepclassmembers class * { @android.webkit.JavascriptInterface <methods>; }
